version: '3.3'

services:
  redis:
    build:
      context: ./redis
      dockerfile: Dockerfile

  httpserver:
    build:
      context: ./httpserver
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    depends_on:
      - redis
